### ISSUE TITLE
Conda install broken; cannot find python modules

### ISSUE THREAD

**Issue by lsmainzer** [miRTop/mirtop#27]
Hey. While testing mirtop, I followed the suggested instructions using Conda. But mirtop is unable to find python modules:

mirtop gff --sps hsa --hairpin hairpin.fa --gtf hsa.gff3 -o  test_out sim_isomir.bam
Traceback (most recent call last):
  File "Testing_mirtop/bin/mirtop", line 9, in <module>
    load_entry_point('mirtop==0.1.8a', 'console_scripts', 'mirtop')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 560, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2648, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2302, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2308, in resolve
  File "Testing_mirtop/mirtop/mirtop/command_line.py", line 7, in <module>
    from mirtop.libs.simulator import simulate
  File "Testing_mirtop/mirtop/mirtop/libs/simulator.py", line 3, in <module>
    from mirtop.libs.read import get_fasta
  File "Testing_mirtop/mirtop/mirtop/libs/read.py", line 8, in <module>
    import pybedtools

**Comment by lpantano** [comment]
Hi,

Thanks for that, I would check the conda recipe to see if I forgot that dependency. It is weird because it is there in the recipe, so not sure why is not installing the tool. 

Just to confirm, did you use?

```
Conda install -c bioconda mirtop
```

Thanks

**Comment by cjfields** [comment]
This might be worth checking in w/ our sysadmins on the cluster, my guess is their version of conda may not allow user-based installs.  If so we'll likely need to install a user- (or group-) specific conda setup.

Just checking, but should we focus on python 2 or 3 for miniconda?

**Comment by lpantano** [comment]
Hi!

Thanks for checking this!

For now, 2.7.
