### ISSUE TITLE
mirtop stats generates empty txt file

### ISSUE THREAD

**Issue by leontienvdbent** [miRTop/mirtop#61]
I installed mirtop v 0.4.22 to process the mirGFF output files generated by miRge2.0. I tried it with miniconda2 (python v2.7) as well as python v3.6 in ubuntu wsl.

When running `$ mirtop stats`, a .txt output file is generated which only contains

'# mirtop stats version 0.4.22 ,category,sample,counts'

This holds true for my own data as well as the example data:

`$ mirtop stats -o test_out examples/gff/correct_file.gff 

['stats', '-o', 'test_out', 'examples/gff/correct_file.gff']                                                                                                 
10/10/2019 12:52:43 WARNING This is devel-live changes                                                                                                       10/10/2019 12:52:43 INFO Run stats.                                                                                                                          10/10/2019 12:52:43 INFO Reading: examples/gff/correct_file.gff                                                                                              10/10/2019 12:52:43 INFO Stats saved at test_out/mirtop_stats.txt                                                                                            10/10/2019 12:52:43 INFO It took 0.000 minutes   `

`$ mirtop gff --gff *.R1_isomiRs.gff -o gff3

['stats', '-o', 'stats', '20729-001.R1_isomiRs.gff', '20729-002.R1_isomiRs.gff', '20729-003.R1_isomiRs.gff', '20729-004.R1_isomiRs.gff', '20729-005.R1_isomiRs.gff', '20729-006.R1_isomiRs.gff', '20729-007.R1_isomiRs.gff', '20729-008.R1_isomiRs.gff', '20729-009.R1_isomiRs.gff', '20729-010.R1_isomiRs.gff', '20729-011.R1_isomiRs.gff', '20729-012.R1_isomiRs.gff', '20729-013.R1_isomiRs.gff', '20729-014.R1_isomiRs.gff', '20729-015.R1_isomiRs.gff', '20729-016.R1_isomiRs.gff', '20729-017.R1_isomiRs.gff', '20729-018.R1_isomiRs.gff', '20729-019.R1_isomiRs.gff', '20729-020.R1_isomiRs.gff', '20729-021.R1_isomiRs.gff', '20729-022.R1_isomiRs.gff', '20729-023.R1_isomiRs.gff', '20729-024.R1_isomiRs.gff', '20729-025.R1_isomiRs.gff', '20729-026.R1_isomiRs.gff', '20729-027.R1_isomiRs.gff']     10/10/2019 01:41:53 WARNING This is devel-live changes                                                                                                       10/10/2019 01:41:53 INFO Run stats.                                                                                                                          10/10/2019 01:41:53 INFO Reading: 20729-001.R1_isomiRs.gff                                                                                                   10/10/2019 01:41:54 INFO Reading: 20729-002.R1_isomiRs.gff                                                                                                   10/10/2019 01:41:55 INFO Reading: 20729-003.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:14 INFO Reading: 20729-004.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:16 INFO Reading: 20729-005.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:17 INFO Reading: 20729-006.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:18 INFO Reading: 20729-007.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:19 INFO Reading: 20729-008.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:20 INFO Reading: 20729-009.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:21 INFO Reading: 20729-010.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:22 INFO Reading: 20729-011.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:23 INFO Reading: 20729-012.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:24 INFO Reading: 20729-013.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:24 INFO Reading: 20729-014.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:25 INFO Reading: 20729-015.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:26 INFO Reading: 20729-016.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:27 INFO Reading: 20729-017.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:28 INFO Reading: 20729-018.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:29 INFO Reading: 20729-019.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:29 INFO Reading: 20729-020.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:30 INFO Reading: 20729-021.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:31 INFO Reading: 20729-022.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:32 INFO Reading: 20729-023.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:33 INFO Reading: 20729-024.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:34 INFO Reading: 20729-025.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:35 INFO Reading: 20729-026.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:35 INFO Reading: 20729-027.R1_isomiRs.gff                                                                                                   10/10/2019 01:42:37 INFO Stats saved at stats/mirtop_stats.txt                                                                                               10/10/2019 01:42:37 INFO It took 0.728 minutes`

I've also tried updating the GFF files, as they are v0.0.1. This gives the following output:

`$ mirtop update -o test_out_mirs 20729-001.R1_isomiRs.gff                          ['update', '-o', 'test_out_mirs', '20729-001.R1_isomiRs.gff']                                                                                                10/10/2019 01:44:11 WARNING This is devel-live changes                                                                                                       10/10/2019 01:44:11 INFO Run update tools                                                                                                                    Traceback (most recent call last):                                                                                                                             File "/mnt/c/Users/mlvanderbent/Ubuntu/miniconda2/bin/mirtop", line 10, in <module>                                                                            sys.exit(main())                                                                                                                                           File "/mnt/c/Users/mlvanderbent/Ubuntu/miniconda2/lib/python2.7/site-packages/mirtop/command_line.py", line 56, in main                                        update.convert(kwargs["args"])                                                                                                                             File "/mnt/c/Users/mlvanderbent/Ubuntu/miniconda2/lib/python2.7/site-packages/mirtop/gff/update.py", line 29, in convert                                       update_file(fn, out_fn)                                                                                                                                    File "/mnt/c/Users/mlvanderbent/Ubuntu/miniconda2/lib/python2.7/site-packages/mirtop/gff/update.py", line 67, in update_file                                   init = versions.index(version)                                                                                                                           ValueError: '0.0.1' is not in list `

Thanks a lot in advance for any tips on how to solve this issue!

**Comment by lpantano** [comment]
Thanks to report this, I will try to figure out what is going on with the test data. Let you know as soon as possible.

**Comment by lpantano** [comment]
Hi,

I made a release. If you install with bioconda it will take one day or so, the pypi should be available already. Can you check if the stats cmd works with the 0.4.23 version?

**Comment by leontienvdbent** [comment]
That's great, thanks a lot @lpantano! I will check it tomorrow as soon as the new version is available and will let you know if it is fixed.

**Comment by leontienvdbent** [comment]
Hi @lpantano , the fix works and the stats function works fine now. Thanks a lot for the quick help!

**Comment by lpantano** [comment]
awesome, thanks for reporting. I will look into the error of not be able to update mirge output.
