### ISSUE TITLE
error when running mirtop gff example tesing

### ISSUE THREAD

**Issue by ylang0825** [miRTop/mirtop#81]
Hello,
I encountered a problem when running the example tesing of mirtop gff function.

I run the mirtop gff as indicated in quick start manual. Here is my code:
$mirtop gff --sps hsa --hairpin examples/annotate/hairpin.fa --gtf examples/annotate/hsa.gff3 -o test_out examples/annotate/sim_isomir_sort.bam

Below is the error presented:
['gff', '--sps', 'hsa', '--hairpin', 'examples/annotate/hairpin_temp.fa', '--gtf', 'examples/annotate/hsa.gff3', '-o', 'test_out', 'examples/annotate/sim_isomir_sort.bam']
06/07/2024 09:34:27 INFO Run annotation
06/07/2024 09:34:27 INFO Reading examples/annotate/sim_isomir_sort.bam
06/07/2024 09:34:27 INFO error at command
Traceback (most recent call last):
  File "/storeData/home/liujunfeng/miniforge3/bin/mirtop", line 8, in <module>
    sys.exit(main())
  File "/storeData/home/liujunfeng/miniforge3/lib/python3.10/site-packages/mirtop/command_line.py", line 31, in main
    reader(kwargs["args"])
  File "/storeData/home/liujunfeng/miniforge3/lib/python3.10/site-packages/mirtop/gff/__init__.py", line 45, in reader
    reads = _read_bam(fn, args)
  File "/storeData/home/liujunfeng/miniforge3/lib/python3.10/site-packages/mirtop/gff/__init__.py", line 94, in _read_bam
    reads = read_bam(bam_fn, precursors)
  File "/storeData/home/liujunfeng/miniforge3/lib/python3.10/site-packages/mirtop/bam/bam.py", line 46, in read_bam
    bam_fn = _bam_sort(bam_fn)
  File "/storeData/home/liujunfeng/miniforge3/lib/python3.10/site-packages/mirtop/bam/bam.py", line 332, in _bam_sort
    do.run(("samtools sort -n -o {bam_sort_by_n} {bam_fn}").format(
  File "/storeData/home/liujunfeng/miniforge3/lib/python3.10/site-packages/mirtop/libs/do.py", line 20, in run
    _do_run(cmd, checks, log_stdout)
  File "/storeData/home/liujunfeng/miniforge3/lib/python3.10/site-packages/mirtop/libs/do.py", line 79, in _do_run
    error_msg += "".join(debug_stdout)
TypeError: sequence item 0: expected str instance, bytes found

Could you please help me find out where the problem is? Thank you very much.

**Comment by ylang0825** [comment]
I found this was because I did not activate the virtual enrivonment. Done already.
